# Data Preprocessing

In [1]:
import pandas as pd

# Importing dataset

In [5]:
dataset = pd.read_csv("sampleMLData.csv")

In [6]:
dataset

country   Age   Salary Purchased
0    spain  27.0  48000.0       Yes
1   France  44.0  72000.0        No
2  Germany  30.0  54000.0        No
3  Germany  40.0      NaN       Yes
4   France  35.0  58000.0       Yes
5    spain   NaN  52000.0        No
6   France  48.0  79000.0       Yes
7  Germany  50.0  83000.0        No
8   France  37.0  67000.0       Yes

In [7]:
dataset.head()

country   Age   Salary Purchased
0    spain  27.0  48000.0       Yes
1   France  44.0  72000.0        No
2  Germany  30.0  54000.0        No
3  Germany  40.0      NaN       Yes
4   France  35.0  58000.0       Yes

In [8]:
dataset.describe()

Age        Salary
count   8.000000      8.000000
mean   38.875000  64125.000000
std     8.219098  13065.084331
min    27.000000  48000.000000
25%    33.750000  53500.000000
50%    38.500000  62500.000000
75%    45.000000  73750.000000
max    50.000000  83000.000000

# Seperating dependent and Independent variable

### dependent variable

In [9]:
x = dataset[["country","Age","Salary"]]

In [10]:
x

country   Age   Salary
0    spain  27.0  48000.0
1   France  44.0  72000.0
2  Germany  30.0  54000.0
3  Germany  40.0      NaN
4   France  35.0  58000.0
5    spain   NaN  52000.0
6   France  48.0  79000.0
7  Germany  50.0  83000.0
8   France  37.0  67000.0

### Dependent Variable

In [11]:
y = dataset[["Purchased"]]

In [12]:
y

Purchased
0       Yes
1        No
2        No
3       Yes
4       Yes
5        No
6       Yes
7        No
8       Yes

In [13]:
type(y)

pandas.core.frame.DataFrame

In [15]:
x = dataset[["country","Age","Salary"]].values

In [16]:
print(x)

[['spain' 27.0 48000.0]
 ['France' 44.0 72000.0]
 ['Germany' 30.0 54000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [17]:
x

array([['spain', 27.0, 48000.0],
       ['France', 44.0, 72000.0],
       ['Germany', 30.0, 54000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [18]:
y = dataset[["Purchased"]].values

In [19]:
y

array([['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [20]:
print(y)

[['Yes']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['Yes']
 ['No']
 ['Yes']]


# Finding missing values

## using SimpleImputer from sklearn module

In [23]:
from sklearn.impute import SimpleImputer
import numpy as np

### replacing all missing values with mean

In [24]:
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

In [26]:
imputer = imputer.fit(x[:,1:3])

In [27]:
x

array([['spain', 27.0, 48000.0],
       ['France', 44.0, 72000.0],
       ['Germany', 30.0, 54000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [28]:
x[:,1:3] = imputer.transform(x[:,1:3])

In [29]:
x

array([['spain', 27.0, 48000.0],
       ['France', 44.0, 72000.0],
       ['Germany', 30.0, 54000.0],
       ['Germany', 40.0, 64125.0],
       ['France', 35.0, 58000.0],
       ['spain', 38.875, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [30]:
from sklearn.preprocessing import LabelEncoder

In [31]:
label_encoder_x = LabelEncoder()

In [32]:
x[:,0] = label_encoder_x.fit_transform(x[:,0])

In [33]:
x

array([[2, 27.0, 48000.0],
       [0, 44.0, 72000.0],
       [1, 30.0, 54000.0],
       [1, 40.0, 64125.0],
       [0, 35.0, 58000.0],
       [2, 38.875, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [34]:
from sklearn.preprocessing import OneHotEncoder

In [35]:
onehotencoder = OneHotEncoder()

In [37]:
x = onehotencoder.fit_transform(dataset.country.values.reshape(-1,1)).toarray()

In [38]:
x

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [39]:
labelencoder_y = LabelEncoder()

In [40]:
y = labelencoder_y.fit_transform(y)

C:\Users\priyanshu verma\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [41]:
y

array([1, 0, 0, 1, 1, 0, 1, 0, 1])

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [44]:
x_train

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [45]:
x_test

array([[0., 1., 0.],
       [0., 1., 0.]])

In [46]:
y_train

array([0, 1, 1, 1, 1, 1, 0])

In [47]:
y_test

array([0, 0])

In [50]:
from sklearn.preprocessing import StandardScaler

In [51]:
sc_x = StandardScaler()

In [52]:
x_train = sc_x.fit_transform(x_train)

In [53]:
x_test = sc_x.transform(x_test)

In [54]:
x_train

array([[ 0.8660254 , -0.40824829, -0.63245553],
       [ 0.8660254 , -0.40824829, -0.63245553],
       [ 0.8660254 , -0.40824829, -0.63245553],
       [ 0.8660254 , -0.40824829, -0.63245553],
       [-1.15470054,  2.44948974, -0.63245553],
       [-1.15470054, -0.40824829,  1.58113883],
       [-1.15470054, -0.40824829,  1.58113883]])

In [55]:
x_test

array([[-1.15470054,  2.44948974, -0.63245553],
       [-1.15470054,  2.44948974, -0.63245553]])